[pytest]
cache_dir = workspace/tmp/.pytest_cache
addopts = -p no:cacheprovider
norecursedirs = .* build dist node_modules __pycache__ dash-diag-* pytest-* tmp* basetemp workspace
filterwarnings =
    ignore:.*HTTP_422_UNPROCESSABLE_ENTITY.*:DeprecationWarning:fastapi\..*
