param(
    [Parameter(Mandatory = $true)]
    [string]$Title,
    [string]$ProjectPath = "g:\Fernando\project0\workspace\projects\SINC"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$adrDir = Join-Path $ProjectPath "ai-orchestrator/documentation/adr"
if (-not (Test-Path -LiteralPath $adrDir)) {
    New-Item -ItemType Directory -Path $adrDir -Force > $null
}

# 1. Determine Next ID
$existingAdrs = Get-ChildItem -Path $adrDir -Filter "ADR-*.md"
$nextId = 1
if ($existingAdrs) {
    $ids = $existingAdrs.Name | ForEach-Object { if ($_ -match "ADR-(\d+)") { [int]$Matches[1] } }
    if ($ids) {
        $nextId = ($ids | Measure-Object -Maximum).Maximum + 1
    }
}
$formattedId = "ADR-{0:0000}" -f $nextId

# 2. Generate Slug
$slug = $Title.ToLower().Replace(" ", "-").Replace("/", "-").Replace("\", "-")
$slug = [regex]::Replace($slug, "[^a-z0-9\-]", "")
$filename = "{0}-{1}.md" -f $formattedId, $slug
$targetPath = Join-Path $adrDir $filename

# 3. Create Content Template (Ensuring ADR-0002 Compliance)
$timestamp = Get-Date -Format "yyyy-MM-ddTHH:mm:ss"
$template = @"
# ${formattedId}: ${Title}

- Date: $timestamp
- Status: Proposed

## Context
Describe the forces at play, including technological, political, social, and project local. 
(Note: This section must be detailed to satisfy documentation standards).

## Decision
What is the change that we're proposing and/or making?
Use bullet points for specific technical contracts or constraints.

## Consequences
What becomes easier or more difficult as a result of this change?
Consider technical debt, performance, and maintenance overhead.

---
*Generated by New-V2ADR.ps1*
"@

# 4. Save
[System.IO.File]::WriteAllText($targetPath, $template)

Write-Host "Created new ADR: $targetPath" -ForegroundColor Green
Write-Host "Please edit the file to provide specific context and details." -ForegroundColor Cyan
