<#
.SYNOPSIS
    Generates docs/context/<module>.md from intake/runtime analysis.
.DESCRIPTION
    Reads modules from:
      1) ai-orchestrator/state/project-state.json (analysis.dependency_graph.modules)
      2) ai-orchestrator/analysis/dependency-graph.md (fallback)
      3) top-level source folders (fallback)
    Creates missing module context files for L3 token-efficient loading.
.PARAMETER ProjectPath
    Project root path.
.PARAMETER OutputDir
    Relative output directory from repository root.
.PARAMETER Force
    Overwrite existing module context files.
#>
param(
    [Parameter(Mandatory)][string]$ProjectPath,
    [string]$OutputDir = "docs/context",
    [switch]$Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Add-Unique {
    param(
        [System.Collections.Generic.List[string]]$List,
        [string]$Value
    )

    if ([string]::IsNullOrWhiteSpace($Value)) { return }
    $trimmed = $Value.Trim()
    if ([string]::IsNullOrWhiteSpace($trimmed)) { return }
    if ($List -notcontains $trimmed) {
        $List.Add($trimmed)
    }
}

$root = Split-Path -Parent $PSScriptRoot
$resolvedProject = if (Test-Path -LiteralPath $ProjectPath) { (Resolve-Path -LiteralPath $ProjectPath).Path } else { $ProjectPath }
if (-not (Test-Path -LiteralPath $resolvedProject -PathType Container)) {
    throw "Project path not found: $ProjectPath"
}

$contextDir = Join-Path $root $OutputDir
New-Item -ItemType Directory -Path $contextDir -Force | Out-Null

$modules = New-Object System.Collections.Generic.List[string]
$projectStatePath = Join-Path $resolvedProject "ai-orchestrator/state/project-state.json"
if (Test-Path -LiteralPath $projectStatePath -PathType Leaf) {
    try {
        $state = Get-Content -LiteralPath $projectStatePath -Raw | ConvertFrom-Json
        $dep = $state.analysis.dependency_graph
        foreach ($module in @($dep.modules)) {
            Add-Unique -List $modules -Value ([string]$module)
        }
    }
    catch {
    }
}

$depGraphMd = Join-Path $resolvedProject "ai-orchestrator/analysis/dependency-graph.md"
if ((Test-Path -LiteralPath $depGraphMd -PathType Leaf) -and $modules.Count -eq 0) {
    $content = Get-Content -LiteralPath $depGraphMd -Raw
    $matches = [regex]::Matches($content, "(?im)^-\s+([A-Za-z0-9_\-./]+)")
    foreach ($m in $matches) {
        Add-Unique -List $modules -Value ([string]$m.Groups[1].Value)
    }
}

if ($modules.Count -eq 0) {
    $codeRoots = @("src", "app", "services", "modules", "lib")
    foreach ($folder in $codeRoots) {
        $candidate = Join-Path $resolvedProject $folder
        if (-not (Test-Path -LiteralPath $candidate -PathType Container)) { continue }
        foreach ($dir in @(Get-ChildItem -LiteralPath $candidate -Directory -Force)) {
            Add-Unique -List $modules -Value ([string]$dir.Name)
        }
    }
}

if ($modules.Count -eq 0) {
    Add-Unique -List $modules -Value "core"
}

$created = 0
$skipped = 0
$projectSlug = Split-Path -Leaf $resolvedProject
$timestamp = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")

foreach ($module in @($modules.ToArray() | Sort-Object)) {
    $fileSlug = ($module -replace "[^A-Za-z0-9_-]+", "-").Trim("-").ToLowerInvariant()
    if ([string]::IsNullOrWhiteSpace($fileSlug)) { $fileSlug = "module" }
    $outPath = Join-Path $contextDir ($fileSlug + ".md")

    if ((Test-Path -LiteralPath $outPath -PathType Leaf) -and -not $Force) {
        $skipped++
        continue
    }

    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("# Module Context: $module")
    $lines.Add("")
    $lines.Add("> Project: $projectSlug")
    $lines.Add("> Generated: $timestamp")
    $lines.Add("> Context layer: L3 (< 800 tokens)")
    $lines.Add("")
    $lines.Add("## Purpose")
    $lines.Add("- [fill] Core responsibility of this module.")
    $lines.Add("")
    $lines.Add("## Key Files")
    $lines.Add("| File | Role |")
    $lines.Add("|------|------|")
    $lines.Add("| - | - |")
    $lines.Add("")
    $lines.Add("## Dependencies")
    $lines.Add("| Depends On | Why |")
    $lines.Add("|------------|-----|")
    $lines.Add("| - | - |")
    $lines.Add("")
    $lines.Add("## Impact Radius")
    $lines.Add("| Used By | Risk |")
    $lines.Add("|---------|------|")
    $lines.Add("| - | - |")
    $lines.Add("")
    $lines.Add("## Domain Rules")
    $lines.Add("- [fill] Invariants and business rules.")
    $lines.Add("")
    $lines.Add("## Known Gaps")
    $lines.Add("- [fill] Open issues, TODOs, constraints.")
    $lines.Add("")
    $lines.Add("## Agent Notes")
    $lines.Add("<!-- [YYYY-MM-DD] [AGENT] [TASK-ID] note -->")
    $lines.Add("")
    $lines.Add("_Auto-generated by `scripts/Generate-ModuleContext.ps1`._")

    [System.IO.File]::WriteAllText($outPath, ($lines -join [Environment]::NewLine))
    $created++
}

Write-Output "Module context generation complete."
Write-Output "Created: $created"
Write-Output "Skipped: $skipped"
Write-Output "Output: $contextDir"
