<#
.SYNOPSIS
    Merges WORLD_MODEL_AUTO output into docs/agents/SYSTEM_MAP.md.
.DESCRIPTION
    Reads auto world model JSON and injects/updates an autogenerated section in SYSTEM_MAP.md.
    This closes the drift between generated domain model and manual architecture map.
.PARAMETER ProjectPath
    Project root path.
.PARAMETER Force
    Overwrites SYSTEM_MAP.md if markers are missing.
#>
param(
    [string]$ProjectPath = ".",
    [switch]$Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Get-OptionalProperty {
    param(
        [object]$InputObject,
        [string]$Name,
        [object]$DefaultValue = $null
    )

    if ($null -eq $InputObject) {
        return $DefaultValue
    }
    if ($InputObject.PSObject.Properties.Name -contains $Name) {
        return $InputObject.$Name
    }
    return $DefaultValue
}

$resolvedProjectPath = if (Test-Path -LiteralPath $ProjectPath) { (Resolve-Path -LiteralPath $ProjectPath).Path } else { $ProjectPath }
if (-not (Test-Path -LiteralPath $resolvedProjectPath -PathType Container)) {
    throw "Project path not found: $ProjectPath"
}

$root = Split-Path -Parent $PSScriptRoot
$projectSlug = Split-Path -Leaf $resolvedProjectPath

$candidateSources = @(
    (Join-Path $resolvedProjectPath "ai-orchestrator/state/world-model-auto.json"),
    (Join-Path $root ("workspace/state/{0}/WORLD_MODEL_AUTO.json" -f $projectSlug))
)

$sourcePath = ""
foreach ($candidate in $candidateSources) {
    if (Test-Path -LiteralPath $candidate -PathType Leaf) {
        $sourcePath = $candidate
        break
    }
}
if ([string]::IsNullOrWhiteSpace($sourcePath)) {
    throw "world-model-auto source not found. Expected ai-orchestrator/state/world-model-auto.json."
}

$source = Get-Content -LiteralPath $sourcePath -Raw | ConvertFrom-Json
$systemMapPath = Join-Path $root "docs/agents/SYSTEM_MAP.md"

if (-not (Test-Path -LiteralPath $systemMapPath -PathType Leaf)) {
    throw "SYSTEM_MAP.md not found: $systemMapPath"
}

$entityCount = [int](Get-OptionalProperty -InputObject (Get-OptionalProperty -InputObject $source -Name "summary" -DefaultValue ([PSCustomObject]@{})) -Name "entity_count" -DefaultValue 0)
$relationshipCount = [int](Get-OptionalProperty -InputObject (Get-OptionalProperty -InputObject $source -Name "summary" -DefaultValue ([PSCustomObject]@{})) -Name "relationship_count" -DefaultValue 0)
$entities = @(Get-OptionalProperty -InputObject $source -Name "entities" -DefaultValue @())
$rules = @(Get-OptionalProperty -InputObject $source -Name "business_rules" -DefaultValue @())

$autoLines = New-Object System.Collections.Generic.List[string]
$autoLines.Add("<!-- AUTO-WORLD-MODEL:START -->")
$autoLines.Add("## Auto World Model (Synced)")
$autoLines.Add("")
$autoLines.Add("- Source: $sourcePath")
$autoLines.Add("- Synced At: $(Get-Date -Format s)")
$autoLines.Add("- Entity Count: $entityCount")
$autoLines.Add("- Relationship Count: $relationshipCount")
$autoLines.Add("")
$autoLines.Add("### Entities")
if ($entities.Count -eq 0) {
    $autoLines.Add("- none detected")
}
else {
    foreach ($entity in $entities) {
        $name = [string](Get-OptionalProperty -InputObject $entity -Name "name" -DefaultValue "")
        if ([string]::IsNullOrWhiteSpace($name)) {
            $name = [string](Get-OptionalProperty -InputObject $entity -Name "key" -DefaultValue "unnamed")
        }
        $type = [string](Get-OptionalProperty -InputObject $entity -Name "type" -DefaultValue "entity")
        $sources = @(
            @(Get-OptionalProperty -InputObject $entity -Name "sources" -DefaultValue @()) |
            ForEach-Object { [string]$_ } |
            Where-Object { -not [string]::IsNullOrWhiteSpace($_) }
        )
        $sourceText = if ($sources.Count -eq 0) { "-" } else { ($sources -join ", ") }
        $autoLines.Add("- $name (`$type=$type`) sources: $sourceText")
    }
}

$autoLines.Add("")
$autoLines.Add("### Business Rules")
if ($rules.Count -eq 0) {
    $autoLines.Add("- none detected")
}
else {
    foreach ($rule in $rules) {
        $autoLines.Add("- " + [string]$rule)
    }
}
$autoLines.Add("<!-- AUTO-WORLD-MODEL:END -->")

$mapContent = Get-Content -LiteralPath $systemMapPath -Raw
$startMarker = "<!-- AUTO-WORLD-MODEL:START -->"
$endMarker = "<!-- AUTO-WORLD-MODEL:END -->"
$autoBlock = ($autoLines -join [Environment]::NewLine)

if ($mapContent -match [regex]::Escape($startMarker) -and $mapContent -match [regex]::Escape($endMarker)) {
    $pattern = "(?s)" + [regex]::Escape($startMarker) + ".*?" + [regex]::Escape($endMarker)
    $updated = [regex]::Replace($mapContent, $pattern, $autoBlock)
    [System.IO.File]::WriteAllText($systemMapPath, $updated)
    Write-Output "SYSTEM_MAP.md auto section updated."
    exit 0
}

if (-not $Force) {
    $updated = $mapContent.TrimEnd() + [Environment]::NewLine + [Environment]::NewLine + $autoBlock + [Environment]::NewLine
    [System.IO.File]::WriteAllText($systemMapPath, $updated)
    Write-Output "SYSTEM_MAP.md auto section appended."
    exit 0
}

[System.IO.File]::WriteAllText($systemMapPath, ($autoBlock + [Environment]::NewLine))
Write-Output "SYSTEM_MAP.md overwritten with auto world model block."
